/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/complicated_roshar_with_buildings.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesher000000_Mesher000000_0092.geometry} material={materials['land material']} />
          <mesh geometry={nodes.ocean100_ocean100_0.geometry} material={materials.ocean100} />
        </group>
      </group>
      <mesh
        geometry={nodes['10076_pisa_tower_v1_max2009_it0'].geometry}
        material={materials['22___Default']}
        position={[-4.49, 27.64, 24.48]}
        scale={0}
      />
    </group>
  )
}

useGLTF.preload('/complicated_roshar_with_buildings.glb')
